name: flutter_jailbreak__root_detection
description: Fork of flutter_jailbreak_detection to include android security privacy policy - Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS. 
version: 1.11.0
homepage: https://github.com/webuijorgeGL/flutter_jailbreak__root_detection

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: appmire.be.flutterjailbreakdetection
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: FlutterJailbreakDetectionPlugin
